### PR TITLE
Test cases for quality measurement metrics

### PR DESCRIPTION
**Pull request by malinthasa**

### CODE REVIEW

**Comment by LinusDietz** [comment]
Hey @malinthasa, I guess the problem with install `pyyaml` is similar to the one described here: can you check it out to get the tests running?
https://stackoverflow.com/questions/29118074/cannot-install-pyyaml-on-travis-ci

**Comment by malinthasa** [comment]
Dear @LinusDietz

I replaced PyYAML with ruamel.yaml as suggested in the StackOverflow answer. That change was built successfully in my local environment and all tests were run.

But I got a similar error while the travis build.

==================================== ERRORS ====================================
____________ ERROR collecting test/quality_metrics/test_filters.py _____________
ImportError while importing test module '/home/travis/build/LinusDietz/tripmining/test/quality_metrics/test_filters.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
test/quality_metrics/test_filters.py:5: in <module>
    from test.quality_metrics.utils import load_trip, prepare_traveler_from_raw_data, imitate_trip_id
test/quality_metrics/utils.py:3: in <module>
    import ruamel.yaml as yaml
E   ModuleNotFoundError: No module named 'ruamel'

Then I tried including explicit installing that dependency in travis.yaml as https://github.com/LinusDietz/tripmining/pull/6/commits/d3d9e9e655a58a6c933220188ef8f05d77eccf4a 

But ended up with the same error.

**Comment by LinusDietz** [comment]
Hi, so what I see is that running `$ sudo pip install ruamel.yaml` will use a different python2 version.

```
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
```

So you could try to install without sudo? (just to see what happens)
```
pip install ruamel.yaml
```

or with sudo: (explicitely choosing the same virtualenv python version)
```
sudo /home/travis/virtualenv/python3.8.0/bin/python -m pip install ruamel.yaml
```

**Comment by malinthasa** [comment]
Dear @LinusDietz ,

Installing the library without sudo worked. Thanks.

**Review by LinusDietz — APPROVED** [review]
Looks alright. Good job!

**Pull request merged**
